---

- name: Configure - List required SAP Notes
  ansible.builtin.debug:
    var: __sap_general_preconfigure_sapnotes_versions | difference([''])

- name: Configure - Create directory '/usr/sap'
  ansible.builtin.file:
    path: '/usr/sap'
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/{{ sap_note_line_item.number }}.yml"
  with_items: "{{ __sap_general_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
