---
- name: Delete Host entries
  hosts: ip-192-168-1-72.eu-west-1.compute.internal
  remote_user: ec2-user
  collections:
    - ansible.controller 
  tasks:

    - name: Gather and manipulate Host Metrics
      ansible.builtin.set_fact:
        host_metrics_ids: "{{ lookup('ansible.controller.controller_api', 'host_metrics', return_all=true) | map(attribute='id') }}"
        
  
    - name: Set the first list
      ansible.builtin.set_fact:
        host_metrics_ids_list1: "{{ host_metrics_ids_list1 | default([]) + [ host_metrics_ids[item|int] ] }}"
      with_sequence: start=0 end=2

    - name: Set the second list
      vars:
        host_list_count: "{{ host_metrics_ids | length - 1 }}"
      ansible.builtin.set_fact:
        host_metrics_ids_list2: "{{ host_metrics_ids_list2 | default([]) + [ host_metrics_ids[item|int] ] }}"
      with_sequence: "start=3 end={{ host_list_count }}"

    # - name: Test new List1 
    #   ansible.builtin.debug:
    #     msg: "{{ host_metrics_ids_list1 }}"

    # - name: Test new List2 
    #   ansible.builtin.debug:
    #     msg: "{{ host_metrics_ids_list2 }}"

    # - name: Test new List 
    #   ansible.builtin.debug:
    #     msg: "{{ host_metrics_ids }}"

    - name: Include tasks for list1
      ansible.builtin.include_tasks:
        file: "../tasks/host_metrix_tasks.yml"
      loop: "{{ host_metrics_ids_list1 }}"

    - name: Include tasks for list2
      ansible.builtin.include_tasks:
        file: "../tasks/host_metrix_tasks.yml"
      loop: "{{ host_metrics_ids_list2 }}"
      



