---
- name: Delete Host entries
  hosts: ip-192-168-1-72.eu-west-1.compute.internal
  remote_user: ec2-user
  collections:
    - ansible.controller 
  tasks:

    - name: Gather and manipulate Host Metrics
      ansible.builtin.set_fact:
        host_metrics_ids: "{{ lookup('ansible.controller.controller_api', 'host_metrics', return_all=true) | map(attribute='id') }}"

    - name: Host List
      ansible.builtin.set_fact:
        host_list: "{{ host_list | default([]) | combine({item: make_key_value}) }}"
      vars:
        host_metrics: "{{ lookup('ansible.controller.controller_api', 'host_metrics/{{ item }}', return_all=true) }}"
        last_automation: "{{ host_metrics.last_automation }}"
        last_automation_split: "{{ last_automation | split('T') | first }}"
        last_automation_calc: "{{ (ansible_date_time.date | to_datetime(format='%Y-%m-%d') - last_automation_split | to_datetime(format='%Y-%m-%d')) }}"
        months_diff: "{{ last_automation_calc | split(' ') | first | int / 30 }}"
        make_key_value:
          hostname: "{{ host_metrics.hostname }}"
          last_automation_date: "{{ months_diff }}" 
          hostname_id: "{{ host_metrics.id }}"
          to_be_deleted: >-
           {% if (months_diff | int) > audit_in_months %}Yes{% else %}No{% endif %}  
      loop: "{{ host_metrics_ids }}"
    
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ host_list[host_metrics_ids] }}"

    - name: Debug 2
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ host_list }}"
      when: item | map(attribute='to_be_deleted') == "Yes"


    - fail:
    
    - name: Test deletion capability
      ansible.builtin.uri:
        url: "https://{{ ansible_hostname }}/api/v2/host_metrics/{{ item }}/"
        method: DELETE
        return_content: yes
        validate_certs: false
        status_code: 204
        headers:
          Authorization: "Bearer {{ lookup('env', 'CONTROLLER_OAUTH_TOKEN') }}"
      loop:
        - 14


