---
- name: Delete Host entries
  hosts: ip-192-168-1-72.eu-west-1.compute.internal
  remote_user: ec2-user
  collections:
    - ansible.controller 
  tasks:

    - name: Gather and manipulate Host Metrics
      ansible.builtin.set_fact:
        host_metrics_ids: "{{ lookup('ansible.controller.controller_api', 'host_metrics', return_all=true) | map(attribute='id') }}"

    - name: Host List
      ansible.builtin.set_fact:
        host_list: "{{ host_list | default({}) | combine({item: make_key_value}) }}"
      vars:
        host_metrics: "{{ lookup('ansible.controller.controller_api', 'host_metrics/{{ item }}', return_all=true) }}"
        last_automation: "{{ host_metrics.last_automation }}"
        last_automation_split: "{{ last_automation | split('T') | first }}"
        make_key_value:
          hostname: "{{ host_metrics.hostname }}"
          last_automation_date: "{{ last_automation_split }}" 
          hostname_id: "{{ host_metrics.id }}"
      loop: "{{ host_metrics_ids }}"
    
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ host_list }}"