---
- name: Check automation hub
  hosts: ip-192-168-1-60.eu-west-1.compute.internal
  tasks:

    - name: Check automation hub | Confirm Web URL is functioning
      ansible.builtin.uri:
        url: "https://{{ ansible_hostname }}/api/galaxy/content/community/"
        status_code: 200
        validate_certs: false
        return_content: true
      ignore_errors: yes
      register: automation_hub_results

    - name: Check automation hub | Install network connection package
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - nmap-ncat
      when: automation_hub_results.status != '200'
  
    - name: Check automation hub | Register port connectivity
      ansible.builtin.command: "nc -v {{ ansible_default_ipv4.address }} {{ item }}"
      loop:
        - '443'
        - '80'
      register: network_connections
      ignore_errors: true
      when: automation_hub_results.status != '200'
    
    - name: debug
      ansible.builtin.debug:
        msg: "{{ network_connections }}"