---
- name: Check execution nodes
  hosts: execution_nodes
  tasks:

    - name: Check execution nodes | Gather Facts about Execution services
      ansible.builtin.service_facts:
      register: service_state_initial
    
    - name: Check execution nodes | Restart {{ item }} service
      ansible.builtin.service:
        service: "{{ item }}"
        state: restarted
      loop:
       - receptor.service  
      when: service_state_initial.ansible_facts.services[item].state != "running"
    
    - name: Check execution nodes | Wait for failed receptor
      ansible.builtin.wait_for:
        timeout: 60
      loop:
       - receptor.service 
      when: service_state_initial.ansible_facts.services[item].state != "running"

    - name: Check execution nodes | Gather Facts about Execution services again
      ansible.builtin.service_facts:
      register: service_state_current
    
    - name: Check execution nodes | Verify the state of Execution service
      ansible.builtin.fail:
        msg: " The {{ item }} is still not working please verify the issue by logging into the Execution node terminal"
      loop:
       - receptor.service
      when: service_state_current.ansible_facts.services[item].state != "running"

    - name: Check execution nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ ansible_hostname }}"
        port: 27199
        state: started
        timeout: 5
      register: local_connections_for_execution
      ignore_errors: true
    
    - name: test more
      debug:
        msg: "{{ local_connections_for_execution }}"

    - name: Check execution nodes | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Local port connections on 27199 cannot be established on this Execution node please verify the issue by logging into Execution node terminal"
      when: local_connections_for_execution.failed == true
    
- name: Check execution nodes continued
  hosts: ip-192-168-1-55.eu-west-1.compute.internal
  collections:
   - infra.ah_configuration
  tasks:

    - name: Check execution nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 27199
        state: started
        timeout: 5
      register: controller_connections_for_execution
      ignore_errors: true
      loop: "{{ groups['execution_nodes'] }}"

    - name: Check automation hub continued | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Ansible Controller port connections on 27199 cannot be established to {{ item }} this is likely due to a Firewall, router or Switch issue"
      loop: "{{ groups['execution_nodes'] }}" 
      loop_control:
        index_var: my_idx
      when: controller_connections_for_execution.results[my_idx].failed == true