---
- name: Check Database nodes
  hosts: database
  tasks:

    - name: Check Database nodes | Gather Facts about Database services
      ansible.builtin.service_facts:
      register: service_state_initial
    
    - name: Check Database nodes | Restart {{ item }} service
      ansible.builtin.service:
        service: "{{ item }}"
        state: restarted
      loop:
       - postgresql.service  
      when: service_state_initial.ansible_facts.services[item].state != "running"
    
    - name: Check Database nodes | Wait for failed receptor
      ansible.builtin.wait_for:
        timeout: 60
      loop:
       - postgresql.service
      when: service_state_initial.ansible_facts.services[item].state != "running"

    - name: Check Database nodes | Gather Facts about Database services again
      ansible.builtin.service_facts:
      register: service_state_current
    
    - name: Check Database nodes | Verify the state of Database service
      ansible.builtin.fail:
        msg: " The {{ item }} is still not working please verify the issue by logging into the Database node terminal"
      loop:
       - postgresql.service
      when: service_state_current.ansible_facts.services[item].state != "running"

    - name: Check Database nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ ansible_hostname }}"
        port: 5432
        state: started
        timeout: 5
      register: local_connections_for_database
      ignore_errors: true
    
    - name: test more
      debug:
        msg: "{{ local_connections_for_database }}"

    - name: Check Database nodes | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Local port connections on 5432 cannot be established on this Database node please verify the issue by logging into Database node terminal"
      when: local_connections_for_database.failed == true
    
- name: Check Database nodes continued
  hosts: ip-192-168-1-55.eu-west-1.compute.internal
  collections:
   - infra.ah_configuration
  tasks:

    - name: Check Database nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 5432
        state: started
        timeout: 5
      register: controller_connections_for_Database
      ignore_errors: true
      loop: "{{ groups['database'] }}"

    - name: Check automation hub continued | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Ansible Controller port connections on 5432 cannot be established to {{ item }} this is likely due to a Firewall, router or Switch issue"
      loop: "{{ groups['database'] }}" 
      loop_control:
        index_var: my_idx
      when: controller_connections_for_database.results[my_idx].failed == true

- name: Check Database nodes continued
  hosts: ip-192-168-1-61.eu-west-1.compute.internal
  collections:
   - infra.ah_configuration
  tasks:

    - name: Check Database nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 5432
        state: started
        timeout: 5
      register: ah_connections_for_database
      ignore_errors: true
      loop: "{{ groups['database'] }}"

    - name: Check Database nodes continued  | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Ansible Automation Hub port connections on 5432 cannot be established to {{ item }} this is likely due to a Firewall, router or Switch issue"
      loop: "{{ groups['database'] }}" 
      loop_control:
        index_var: my_idx
      when: ah_connections_for_database.results[my_idx].failed == true