---
- name: Check automation controller nodes
  hosts: automationcontroller
  tasks:

    - name: Check automation controller nodes | Gather Facts about automation controller services
      ansible.builtin.service_facts:
      register: service_state_initial
        
    - name: Check automation controller nodes | Restart {{ item }} service
      ansible.builtin.service:
        service: "{{ item | split('.') | first }}"
        state: restarted
      loop:
       - "receptor.service"
       - "nginx.service"
      when: service_state_initial.ansible_facts.services[item].state != "running"
    
    - name: Check automation controller nodes | Wait for failed Service
      ansible.builtin.wait_for:
        timeout: 60
      loop:
       - "receptor.service"
       - "automation-controller.service"
       - "nginx.service"
      when: service_state_initial.ansible_facts.services[item].state != "running"

    - name: Check automation controller nodes | Gather Facts about automation controller services again
      ansible.builtin.service_facts:
      register: service_state_current
    
    - name: Check automation controller nodes | Verify the state of automation controller service
      ansible.builtin.fail:
        msg: " The {{ item }} is still not working please verify the issue by logging into the automation controller node terminal"
      loop:
       - "receptor.service"
       - "automation-controller.service"
       - "nginx.service"
      when: service_state_current.ansible_facts.services[item].state != "running"

    - name: Check automation controller nodes continued | Test network connection
      ansible.builtin.wait_for:
        host: "{{ ansible_hostname }}"
        port: 443
        state: started
        timeout: 5
      register: local_connections_for_automationcontroller
      ignore_errors: true
    
    - name: test more
      debug:
        msg: "{{ local_connections_for_automationcontroller }}"

    - name: Check automation controller nodes | Confirm port connectivity
      ansible.builtin.fail:
        msg: "Local port connections on 443 cannot be established on this automation controller node please verify the issue by logging into automation controller node terminal"
      when: local_connections_for_automationcontroller.failed == true
    
