---

- name: Assert 3108316-3
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 3: Configure Hostname"

- name: Import tasks from '../../RedHat/generic/assert-hostname.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-hostname.yml

- name: Import tasks from '../../RedHat/generic/assert-etc-hosts.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-etc-hosts.yml

- name: Import tasks from '../../RedHat/generic/assert-dns-name-resolution.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-dns-name-resolution.yml
