---

- name: Configure 3108316-3
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 3: Configure Hostname"

- name: Import tasks from '../../RedHat/generic/configure-hostname.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-hostname.yml

- name: Import tasks from '../../RedHat/generic/configure-etc-hosts.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-etc-hosts.yml

- name: Import tasks from '../../RedHat/generic/check-dns-name-resolution.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/check-dns-name-resolution.yml
