---

- name: Configure 3108316-8
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 8: Configure Linux Kernel Parameters"

- name: Import tasks from '../../RedHat/generic/configure-kernel-parameters.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/configure-kernel-parameters.yml
