---

- name: Assert 3108316-9
  ansible.builtin.debug:
    msg: "SAP note 3108316 Step 9: Configure Process Resource Limits"

- name: Import tasks from '../../RedHat/generic/assert-limits-conf-file.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-limits-conf-file.yml

- name: Import tasks from '../../RedHat/generic/assert-nproc-limits.yml'
  ansible.builtin.import_tasks: ../../RedHat/generic/assert-nproc-limits.yml
