---

- name: SAP Install Media Detect - SAPCAR - Get SAPCAR executable file from folder - {{ __sap_install_media_detect_software_main_directory }}
  ansible.builtin.shell: ls SAPCAR*.EXE
  args:
    chdir: "{{ __sap_install_media_detect_software_main_directory }}"
  register: sap_swpm_sapcar_file_name_get
  changed_when: false

- name: SAP Install Media Detect - SAPCAR - Set fact
  ansible.builtin.set_fact:
    sap_swpm_sapcar_file_name: "{{ sap_swpm_sapcar_file_name_get.stdout }}"

- name: SAP Install Media Detect - SAPCAR - Change ownership of SAPCAR
  ansible.builtin.file:
    path: "{{ __sap_install_media_detect_software_main_directory }}/{{ sap_swpm_sapcar_file_name }}"
    state: file
    mode: '0755'
    owner: root
    group: root
