---

- name: SAP Install Media Detect - SAP IGS - Get IGS from software path
  ansible.builtin.shell: ls igsexe*.sar
  args:
    chdir: "{{ sap_swpm_software_path }}"
  register: sap_swpm_igs_file_name_get
  changed_when: false

- name: SAP Install Media Detect - SAP IGS - Set fact for IGS
  ansible.builtin.set_fact:
    sap_swpm_igs_path: "{{ sap_swpm_software_path }}"
    sap_swpm_igs_file_name: "{{ sap_swpm_igs_file_name_get.stdout }}"

# failed_when will trigger if more than 1 igsexe is identified and added to the register
- name: SAP Install Media Detect - SAP IGS - Check availability of IGS - {{ sap_swpm_igs_path }}/{{ sap_swpm_igs_file_name }}
  ansible.builtin.stat:
    path: "{{ sap_swpm_igs_path }}/{{ sap_swpm_igs_file_name }}"
  register: sap_swpm_igs_file_name_stat
  failed_when: not sap_swpm_igs_file_name_stat.stat.exists

# 4. IGS Helper
- name: SAP Install Media Detect - SAP IGS - Get IGS Helper from software path
  ansible.builtin.shell: ls igshelper*.sar
  args:
    chdir: "{{ sap_swpm_software_path }}"
  register: sap_swpm_igs_helper_file_name_get
  changed_when: false

- name: SAP Install Media Detect - SAP IGS - Set fact for IGS
  ansible.builtin.set_fact:
    sap_swpm_igs_helper_path: "{{ sap_swpm_software_path }}"
    sap_swpm_igs_helper_file_name: "{{ sap_swpm_igs_helper_file_name_get.stdout }}"

- name: SAP Install Media Detect - SAP IGS - Check availability of IGS Helper - {{ sap_swpm_igs_helper_path }}/{{ sap_swpm_igs_helper_file_name }}
  ansible.builtin.stat:
    path: "{{ sap_swpm_igs_helper_path }}/{{ sap_swpm_igs_helper_file_name }}"
  register: sap_swpm_igs_helper_file_name_stat
  failed_when: not sap_swpm_igs_helper_file_name_stat.stat.exists
