---

- name: SAP Install Media Detect - SAP Host Agent - Set fact for install media directory
  ansible.builtin.set_fact:
    sap_hostagent_install_directory: "{{ __sap_install_media_detect_software_main_directory }}/sap_hostagent"

- name: SAP Install Media Detect - SAP Host Agent - Create Directory - {{ sap_hostagent_install_directory }}
  ansible.builtin.file:
    path: "{{ sap_hostagent_install_directory }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

# SAPHOSTAGENT
- name: SAP Install Media Detect - SAP Host Agent - Get SAPHOSTAGENT SAR file from folder - {{ __sap_install_media_detect_software_main_directory }}
  ansible.builtin.shell: ls SAPHOSTAGENT*SAR
  args:
    chdir: "{{ __sap_install_media_detect_software_main_directory }}"
  register: saphostagent_sarfile
  changed_when: false

- name: SAP Install Media Detect - SAP Host Agent - Copy SAPHOSTAGENT SAR file
  ansible.builtin.shell: |
    cp {{ __sap_install_media_detect_software_main_directory }}/{{ saphostagent_sarfile.stdout }} {{ sap_hostagent_install_directory }}/{{ saphostagent_sarfile.stdout }}
  changed_when: true
