---

- name: Identify SAP HANA Backup files
  ansible.builtin.find:
    paths: "{{ sap_install_media_detect_backup_directory }}"
    recurse: true
    file_type: directory
    patterns: '.*COMPLETE.*'
    use_regex: true
  register: backup_saphana_find_dir
