name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: |
        pip3 install ansible-lint
        ansible-lint -p roles/ -c .github/workflows/ansible-lint-config

# Static: use Ansible Community Edition 4.8.0, with lowest compatible Ansible Core 2.11.6 and use Ansible-lint 5.2.1
