download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-sap_install-1.3.1.tar.gz
format_version: 1.0.0
name: sap_install
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.3.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/sap_install/versions/1.3.1/
