---
# Clean backups for single SID
- name: SAP HANA Backint - Clean - sap_hana_sid is provided
  block:
    - name: SAP HANA Backint - Clean - Clean backups for {{ sap_hana_sid }}
      ansible.builtin.include_tasks: clean_backups.yml
  when: sap_hana_sid != "all"

# Clean backups for each SID - loop through {{ sap_hana_sid_all }}
# Loop is equivalent to with_list, and must not be a string
- name: SAP HANA Backint - Clean - All HDB SIDs in hostname {{ ansible_hostname }}
  block:
    - name: SAP HANA Backint - Clean - Clean backups for each SID
      ansible.builtin.include_tasks: clean_backups.yml
      register: clean_backups_reg
      loop: "{{ sap_hana_sid_all }}"
      loop_control:
        loop_var: passed_sap_hana_sid
  when: sap_hana_sid == "all"
