---
- name: SAP HANA Backint - Clean - Execute hanacleaner.py for SYSTEMDB - {{ passed_sap_hana_sid }}
  ansible.builtin.shell: |
    source ~/.profile && python {{ backint_directory }}/hanacleaner.py -k {{ system_backup_user }} -be {{ backup_retention }} -bb true
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ passed_sap_hana_sid | lower }}adm"
  register: sap_hana_backint_clean_execute_hanacleaner

- name: SAP HANA Backint - Clean - Output hanacleaner execution
  ansible.builtin.debug:
    msg: "{{ sap_hana_backint_clean_execute_hanacleaner }}.stdout_lines"
