---
- name: SAP HANA Backint - Execute - Set fact for SID
  ansible.builtin.set_fact:
    passed_sap_hana_sid: "{{ sap_hana_sid }}"
  when: sap_hana_sid != "all"

# Set hdbuserstore users
- name: SAP HANA Backint - Execute - Set facts for hdbuserstore users
  ansible.builtin.set_fact:
    tenant_backup_user: "HDB_TENANT_{{ passed_sap_hana_sid }}_BACKUP_USER"

- name: SAP HANA Backint - Output executing information
  ansible.builtin.debug:
    msg:
      - "Executing backup for: "
      - "SAP HANA SID   -     {{ passed_sap_hana_sid }} "
      - "Hostname       -     {{ ansible_hostname }} "

# Execute backup for SYSTEMDB
- name: SAP HANA Backint - Execute - SYSTEMDB - {{ passed_sap_hana_sid }}
  ansible.builtin.include_tasks: execute_backup_systemdb.yml

# Execute backup for Tenant DBs - loop through {{ sap_hana_tenant }}
- name: SAP HANA Backint - Execute - TENANTDB - {{ passed_sap_hana_sid }}
  ansible.builtin.include_tasks: execute_backup_tenants.yml
  register: backup_hana_tenant
  loop: "{{ sap_hana_tenant }}"
  loop_control:
    loop_var: passed_sap_hana_tenant
