---
# Execute backups for single SID
- name: SAP HANA Backint - Execute - sap_hana_sid is provided
  block:
    - name: SAP HANA Backint - Execute - Execute backups for {{ sap_hana_sid }}
      ansible.builtin.include_tasks: execute_backup.yml
  when: sap_hana_sid != "all"

# Execute backups for each SID - loop through list {{ sap_hana_sid_all }}
# Loop is equivalent to with_list, and must not be a string
- name: SAP HANA Backint - Execute - All HDB SIDs in hostname {{ ansible_hostname }}
  block:
    - name: SAP HANA Backint - Execute - Execute backups for each SID
      ansible.builtin.include_tasks: execute_backup.yml
      register: execute_backup_reg
      loop: "{{ sap_hana_sid_all }}"
      loop_control:
        loop_var: passed_sap_hana_sid
  when: sap_hana_sid == "all"

- name: SAP HANA Backint - Output NOTICE
  ansible.builtin.debug:
    msg:
      - "Please note that backups were triggered in the background"
