---
# The SAP ID must follow a strict format and not use reserved special values
# TODO: This check may be better placed in a SAP role earlier in the chain...
- name: "SAP HA Prepare Pacemaker - Validate SAP System ID (SAP HANA)"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_hana_sid | length == 3
      - sap_ha_pacemaker_cluster_hana_sid not in __sap_sid_prohibited
  when:
    - "'hana' in sap_ha_pacemaker_cluster_host_type"
    - sap_ha_pacemaker_cluster_hana_sid is defined
    - sap_ha_pacemaker_cluster_hana_sid | length > 0

- name: "SAP HA Prepare Pacemaker - Validate SAP System ID (SAP Netweaver)"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_netweaver_sid | length == 3
      - sap_ha_pacemaker_cluster_netweaver_sid not in __sap_sid_prohibited
  when:
    - "'nwas' in sap_ha_pacemaker_cluster_host_type"
    - sap_ha_pacemaker_cluster_netweaver_sid is defined
    - sap_ha_pacemaker_cluster_netweaver_sid | length > 0

- name: "SAP HA Prepare Pacemaker - Verify that a SID is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_hana_sid is defined
        or sap_ha_pacemaker_cluster_netweaver_sid is defined
      - sap_ha_pacemaker_cluster_hana_sid | length > 0
        or sap_ha_pacemaker_cluster_netweaver_sid | length > 0
