# Update known hosts file - $HOME/.ssh/known_hosts
---

- name: Scan ssh public key for each host
  ansible.builtin.shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
  with_items: "{{ ssh_known_hosts }}"
  register: ssh_known_host_results
  ignore_errors: true

- name: Add/update public key in the '{{ ssh_known_hosts_file }}'
  ansible.builtin.known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    path: "{{ ssh_known_hosts_file }}"
  with_items: "{{ ssh_known_host_results.results }}"
