- name: SAP Firewall - Generate Ports - SAP NW - {{ sap_firewall_instance_nr }}
  ansible.builtin.set_fact:
    sap_firewall_ports:
      - "3200-3399"
      - "36{{ sap_firewall_instance_nr }}"
      - "80{{ sap_firewall_instance_nr }}"
      - "81{{ sap_firewall_instance_nr }}"
      - "443{{ sap_firewall_instance_nr }}"
      - "620{{ sap_firewall_instance_nr }}"
      - "621{{ sap_firewall_instance_nr }}"
      - "5{{ sap_firewall_instance_nr }}13"
      - "5{{ sap_firewall_instance_nr }}14"
      - "5{{ sap_firewall_instance_nr }}16"
      - "44390"
      - "8090"
