---
# This task requires the variable passed_port

- name: SAP Firewall - Update Firewall - {{ passed_port }}/tcp
  ansible.posix.firewalld:
    zone: public
    port: "{{ passed_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled
