---

- name: Ensure required packages for SAP NetWeaver are installed
  ansible.builtin.package:
    state: present
    name: "{{ __sap_netweaver_preconfigure_packages }}"

#The use of zypper here allows exact saptune version to be declared and used.
- name: Ensure saptune is installed
  community.general.zypper:
    type: package
    name: "saptune={{ sap_netweaver_preconfigure_saptune_version }}"
    state: present
    force: yes
