---
# passed_parameter.split()[0] = first word of passed_parameter used as regex
# Add comment using:
#     line: "# Updated by sap_profile_update - {{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"') }}\n{{ passed_parameter }}"

- name: Update "{{ passed_parameter }}"
  ansible.builtin.lineinfile:
    path: "{{ passed_parameter_path }}"
    regexp: "^{{ passed_parameter.split()[0] }}"
    line: "{{ passed_parameter }}"
    owner: "{{ sap_update_profile_sid | lower }}adm"
    group: sapsys
    mode: "0644"
