- name: SAP OS Tools - RedHat Subscription Manager - Refresh - {{ ansible_distribution }} - {{ ansible_distribution_version }}
  block:
    - name: Subscription Manager - Refresh
      ansible.builtin.command: "subscription-manager refresh"

    - name: Subscription Manager - Identity Regenerate
      ansible.builtin.command: "subscription-manager identity --regenerate"

    - name: Subscription Manager - Lock Release
      ansible.builtin.command: "subscription-manager release --set={{ ansible_distribution_version }}"

    - name: Yum clean all
      ansible.builtin.command: "yum clean all"

    - name: Clear dnf cache
      ansible.builtin.file:
        path: /var/cache/dnf
        state: absent

    - name: Clear rhsm packages
      ansible.builtin.file:
        path: /var/lib/rhsm/packages/packages.json
        state: absent

    - name: Restart service rhsmcertd
      ansible.builtin.service:
        name: rhsmcertd
        state: restarted

  when: ansible_facts['distribution'] == 'RedHat'
