---
# This task requires the variable sap_fapolicy_sid

- name: Get sidadm user of "{{ sap_fapolicy_sid }}"
  ansible.builtin.set_fact:
    sidadm_user: "{{ sap_fapolicy_sid | lower }}adm"
  register: get_sidadm_user_register

# Return value
- name: Return value from previous fact
  ansible.builtin.set_fact:
    sap_fapolicy_user: "{{ sidadm_user.split() }}"
# - name: Merge the sap_fapolicy_user_list with result
#   set_fact:
#     sap_fapolicy_user_list: "{{ sap_fapolicy_user_list + get_sidadm_user_return }}"
