---
# This task requires the variable sap_hana_sid and hdbuserstore system_backup_user

- name: SAP HANA Backint - Get info - Get Tenant DBs of SAP HANA Database Server {{ sap_hana_sid }}
  ansible.builtin.shell: |
    /usr/sap/{{ sap_hana_sid }}/SYS/exe/hdb/hdbsql -x -a -U {{ system_backup_user }} "select DATABASE_NAME from SYS.M_DATABASES WHERE DATABASE_NAME != 'SYSTEMDB'" | sed 's/\"//g'
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_hana_sid | lower }}adm"
  register: get_all_sap_hana_tenant

#  Code below doesnt work when running in crontab
# - name: Get Tenant DBs of SAP HANA Database Server {{ sap_hana_sid }}
#   shell: |
#     su - {{ sap_hana_sid | lower }}adm -c "hdbsql -x -a -U {{ system_backup_user }} \"select DATABASE_NAME from SYS.M_DATABASES WHERE DATABASE_NAME != 'SYSTEMDB'\" | sed 's/\"//g'"
#   register: get_all_sap_hana_tenant

# Return value - sap_hana_tenant
- name: SAP HANA Backint - Get info - Set facts for all SAP HANA Tenants
  ansible.builtin.set_fact:
    sap_hana_tenant: "{{ get_all_sap_hana_tenant.stdout.split() }}"
