---
# This task requires the variable sap_hana_sid

- name: SAP HANA Backint - Get info - Get Tenant DBs of SAP HANA Database Server {{ sap_hana_sid }}
  ansible.builtin.shell: |
    while read LINE
    do
      ### Check to see if /usr/sap/SID exists. If not then its probably not used anymore / its not a SID so ignore
      if [ -d /usr/sap/$LINE ]; then
        # $LINE is an HDB system
        SAP_HDB_SID_ARRAY+=( "$LINE" )
      else
        # $LINE not in /usr/sap
        :
      fi
    done < <(ls -1 /hana/shared)

    echo "${SAP_HDB_SID_ARRAY[@]}"
  args:
    executable: /bin/bash
  register: get_all_sap_hana_sid

# Return value - sap_hana_sid_all
- name: SAP HANA Backint - Get info - Set facts for all SAP HANA System IDs (SIDs)
  ansible.builtin.set_fact:
    sap_hana_sid_all: "{{ get_all_sap_hana_sid.stdout.split() }}"
