---
# This task requires the variable sap_hana_sid

- name: SAP HANA Backint - Get info - Get instance number of SAP HANA Database Server {{ sap_hana_sid }}
  ansible.builtin.shell: |
    ls -1 /usr/sap/{{ sap_hana_sid }} | grep HDB | sed 's/...//' | head -1
  args:
    executable: /bin/bash
  register: get_sap_hana_instance_nr

# Return value - sap_hana_instance_nr_one
- name: SAP HANA Backint - Get info - Set facts for SAP HANA Instance Number
  ansible.builtin.set_fact:
    sap_hana_instance_nr_one: "{{ get_sap_hana_instance_nr.stdout.split() }}"
