- name: SAP OS Tools - /etc/hosts - Split passed entry
  ansible.builtin.set_fact:
    passed_ip: "{{ passed_entry.split()[0] }}"
    passed_host: "{{ passed_entry.split()[1] }}"

- name: SAP OS Tools - /etc/hosts - Deduplicate values from /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    create: false
    regexp: (?i)^\s*{{ passed_ip }}\s+
    state: absent

- name: SAP OS Tools - /etc/hosts - Update
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ passed_ip }}{{ os_etchosts_delimiter }}{{ passed_host }}.{{ os_etchosts_fqdn }}{{ os_etchosts_delimiter }}{{ passed_host }}"
