download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-sap_launchpad-1.0.1.tar.gz
format_version: 1.0.0
name: sap_launchpad
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/sap_launchpad/versions/1.0.1/
